def build_pending_flow_kwargs(
    *,
    message,
    token,
    session,
    pending_create_schedule,
    pending_delete_schedule,
    pending_employee_operation,
    operations,
    call_api,
    clear_pending_create_schedule_state,
    clear_pending_delete_schedule_state,
    extract_schedule_name_or_id_from_message,
    normalize_schedule_id_arg,
    lookup_schedule_name_by_id,
    extract_employee_name_parts,
    extract_role_id,
    extract_explicit_employee_id,
    resolve_employee_id,
    set_pending_employee_operation_state,
    clear_pending_employee_operation_state,
):
    return {
        "message": message,
        "token": token,
        "session": session,
        "pending_create_schedule": pending_create_schedule,
        "pending_delete_schedule": pending_delete_schedule,
        "pending_employee_operation": pending_employee_operation,
        "operations": operations,
        "call_api": call_api,
        "clear_pending_create_schedule_state": clear_pending_create_schedule_state,
        "clear_pending_delete_schedule_state": clear_pending_delete_schedule_state,
        "extract_schedule_name_or_id_from_message": extract_schedule_name_or_id_from_message,
        "normalize_schedule_id_arg": normalize_schedule_id_arg,
        "lookup_schedule_name_by_id": lookup_schedule_name_by_id,
        "extract_employee_name_parts": extract_employee_name_parts,
        "extract_role_id": extract_role_id,
        "extract_explicit_employee_id": extract_explicit_employee_id,
        "resolve_employee_id": resolve_employee_id,
        "set_pending_employee_operation_state": set_pending_employee_operation_state,
        "clear_pending_employee_operation_state": clear_pending_employee_operation_state,
    }


def build_shift_flow_kwargs(
    *,
    message,
    token,
    session,
    pending_shift,
    pending_delete_shift,
    pending_update_shift,
    explicit_employee_id,
    operations,
    is_create_shift_intent,
    is_delete_shift_intent,
    is_update_shift_intent,
    find_name_in_message,
    resolve_employee_id,
    set_pending_employee_disambiguation_state,
    build_employee_disambiguation_prompt,
    extract_weekday_date,
    resolve_disambiguation_reply,
    attempt_fill_shift_state_from_message,
    build_create_shift_question,
    next_missing_shift_field,
    format_shift_option_line,
    resolve_delete_shift_number_reply,
    resolve_shift_number_reply,
    extract_time_of_day,
    extract_duration_hours,
    clear_pending_delete_shift_state,
    set_pending_delete_shift_state,
    clear_pending_update_shift_state,
    set_pending_update_shift_state,
    set_pending_shift_state,
    clear_pending_shift_state,
    normalize_schedule_id_arg,
    call_api,
    week_range_from_date,
):
    return {
        "message": message,
        "token": token,
        "session": session,
        "pending_shift": pending_shift,
        "pending_delete_shift": pending_delete_shift,
        "pending_update_shift": pending_update_shift,
        "explicit_employee_id": explicit_employee_id,
        "operations": operations,
        "is_create_shift_intent": is_create_shift_intent,
        "is_delete_shift_intent": is_delete_shift_intent,
        "is_update_shift_intent": is_update_shift_intent,
        "find_name_in_message": find_name_in_message,
        "resolve_employee_id": resolve_employee_id,
        "set_pending_employee_disambiguation_state": set_pending_employee_disambiguation_state,
        "build_employee_disambiguation_prompt": build_employee_disambiguation_prompt,
        "extract_weekday_date": extract_weekday_date,
        "resolve_disambiguation_reply": resolve_disambiguation_reply,
        "attempt_fill_shift_state_from_message": attempt_fill_shift_state_from_message,
        "build_create_shift_question": build_create_shift_question,
        "next_missing_shift_field": next_missing_shift_field,
        "format_shift_option_line": format_shift_option_line,
        "resolve_delete_shift_number_reply": resolve_delete_shift_number_reply,
        "resolve_shift_number_reply": resolve_shift_number_reply,
        "extract_time_of_day": extract_time_of_day,
        "extract_duration_hours": extract_duration_hours,
        "clear_pending_delete_shift_state": clear_pending_delete_shift_state,
        "set_pending_delete_shift_state": set_pending_delete_shift_state,
        "clear_pending_update_shift_state": clear_pending_update_shift_state,
        "set_pending_update_shift_state": set_pending_update_shift_state,
        "set_pending_shift_state": set_pending_shift_state,
        "clear_pending_shift_state": clear_pending_shift_state,
        "normalize_schedule_id_arg": normalize_schedule_id_arg,
        "call_api": call_api,
        "week_range_from_date": week_range_from_date,
    }
